In [ ]:
import numpy as np # importing NumPy as "np" is a standard and reduces code length by a bit

In [5]:
normal_list = [1, 2, 3, 4, 5]
nd_array = np.array(normal_list)
print(f"Normal list: {normal_list}, n D Array: {nd_array}")
print(f"Normal list: {type(normal_list)}, n D Array: {type(nd_array)}")

Normal list: [1, 2, 3, 4, 5], n D Array: [1 2 3 4 5]
Normal list: <class 'list'>, n D Array: <class 'numpy.ndarray'>


In [6]:
nd_array.mean() # Calculates the average

np.float64(3.0)

In [7]:
nd_array.max(), nd_array.min() # Gets the minimum and maximum values

(np.int64(5), np.int64(1))

In [9]:
nd_array.sum() # Calculates the summation across the whole array

np.int64(15)

In [10]:
nd_array + 1 # Adds one to each element in the array
nd_array - 1 # Subtracts one from each element in the array
nd_array * 1 # Multiplies each element from the array by 1
nd_array / 1 # Divides each element from the array by 1
# The output will remain the same since we did nothing 

array([1., 2., 3., 4., 5.])

In [ ]:
nd_array.shape # Returns the dimensions of the array, since there is only one dimension and it has five elements, the shape is (5,)

(5,)

In [ ]:
nd_array.dtype # Returns the type of the data stored in the array

dtype('int64')

In [ ]:
nd_array.ndim # Returns the number of dimensions

1

In [14]:
random_int_array = np.random.randint(
    low=1, # The lowest value that can be chosen
    high=10, # The highest value that can be chosen
    size=5, # the shape/length of the array 
)
random_int_array

array([2, 1, 7, 5, 8])

In [34]:
random_float_array = np.random.rand(2, 2) # takes only the shape. NOTE: the shape is NOT a tuple
random_float_array

array([[0.30684619, 0.05161141],
       [0.8260063 , 0.03290276]])

In [ ]:
binomial_array = np.random.binomial(n=10, p=0.5, size=(2, 4)) # Returns a Binomial Distribution random array
binomial_array

array([[5, 6, 4, 4],
       [7, 5, 7, 8]])

In [ ]:
geometric_array = np.random.geometric(p=0.5, size=(3, 4)) # Returns a Geometric Distribution random array
geometric_array

array([[2, 1, 1, 4],
       [4, 1, 1, 1],
       [1, 2, 5, 1]])

In [51]:
matrix= np.random.randint(low=1, high=10, size=(2, 2))
matrix

array([[7, 1],
       [7, 7]])

In [52]:
matrix + 2

array([[9, 3],
       [9, 9]])

In [53]:
matrix * 3

array([[21,  3],
       [21, 21]])

In [54]:
matrix - 4

array([[ 3, -3],
       [ 3,  3]])

In [ ]:
matrix + matrix # Each element is added to the coressponding on in the other matrix

array([[14,  2],
       [14, 14]])

In [57]:
one_d_array = np.random.randint(low=1, high=10, size=5)
one_d_array

array([7, 8, 2, 3, 3])

In [58]:
two_d_array = np.random.randint(low=1, high=10, size=(5, 5))
two_d_array

array([[8, 3, 4, 8, 2],
       [4, 7, 2, 2, 1],
       [1, 6, 9, 4, 7],
       [1, 3, 7, 4, 4],
       [3, 1, 1, 1, 7]])

In [59]:
two_d_array + one_d_array

array([[15, 11,  6, 11,  5],
       [11, 15,  4,  5,  4],
       [ 8, 14, 11,  7, 10],
       [ 8, 11,  9,  7,  7],
       [10,  9,  3,  4, 10]])

In [60]:
two_d_array * one_d_array

array([[56, 24,  8, 24,  6],
       [28, 56,  4,  6,  3],
       [ 7, 48, 18, 12, 21],
       [ 7, 24, 14, 12, 12],
       [21,  8,  2,  3, 21]])

In [65]:
wrong_size_array = np.random.randint(low=1, high=10, size=6)
wrong_size_array

array([3, 1, 8, 9, 5, 7])

In [66]:
two_d_array + wrong_size_array # Throws an error due to incompatible sizes

ValueError: operands could not be broadcast together with shapes (5,5) (6,) 

In [68]:
arr1 = np.random.randint(low=1, high=10, size=(2, 3))
arr1

array([[5, 8, 2],
       [1, 6, 1]])

In [70]:
arr2 = np.random.randint(low=1, high=10, size=(3, 4))
arr2

array([[1, 7, 8, 6],
       [6, 2, 3, 1],
       [5, 9, 1, 4]])

In [71]:
arr1 @ arr2 # matrix of size 2 x 3 with 3 x 4 => a matrix of size 2 x 4 

array([[63, 69, 66, 46],
       [42, 28, 27, 16]])

In [72]:
arr1.dot(arr2) # same result

array([[63, 69, 66, 46],
       [42, 28, 27, 16]])

In [73]:
(arr1 @ arr2) == (arr1.dot(arr2)) # sanity check

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [74]:
wrong_size_array = np.random.randint(low=1, high=10, size=(5, 5))

In [76]:
wrong_size_array @ arr2 # sizes 5 x 5 and 3 x 4 are incompatible => error

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)